<?xml version="1.0"?>
<robot name="vacuum_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Parámetros básicos -->
  <xacro:property name="base_length" value="0.30"/>
  <xacro:property name="base_width"  value="0.28"/>
  <xacro:property name="base_height" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width"  value="0.02"/>
  <xacro:property name="wheel_sep"    value="0.22"/>

  <xacro:property name="caster_radius" value="0.015"/>

  <!-- Materiales simples -->
  <material name="gray"><color rgba="0.6 0.6 0.6 1"/></material>
  <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>

  <!-- BASE -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.08"/>
      </geometry>
      <material name="gray"/>
    </visual>

    <collision>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.08"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
               iyy="0.05" iyz="0.0"
               izz="0.08"/>
    </inertial>
  </link>


  <!-- RUEDA IZQUIERDA -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0002" ixy="0" ixz="0"
               iyy="0.0002" iyz="0"
               izz="0.0002"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_sep/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- RUEDA DERECHA -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0002" ixy="0" ixz="0"
               iyy="0.0002" iyz="0"
               izz="0.0002"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-wheel_sep/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- CASTER (rueda loca / esfera simple) -->
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.00001" ixy="0" ixz="0"
               iyy="0.00001" iyz="0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <!-- caster al frente -->
    <origin xyz="${base_length/2 - 0.04} 0 ${caster_radius}" rpy="0 0 0"/>
  </joint>
  
    <!-- Torreta LIDAR (visual) -->
  <link name="lidar_turret_link">
    <visual>
      <origin xyz="0 0 0.095" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.035" length="0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.095" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.035" length="0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0"
               iyy="0.0001" iyz="0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_turret_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_turret_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Frame del LIDAR (donde luego saldrá /scan) -->
  <link name="laser_link"/>
  <joint name="laser_joint" type="fixed">
    <parent link="lidar_turret_link"/>
    <child link="laser_link"/>
    <origin xyz="0 0 0.015" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR Gazebo -->
  <gazebo reference="laser_link">
  <sensor type="ray" name="lidar_sensor">
    <pose>0 0 0 0 0 0</pose>
    <visualize>true</visualize>
    <update_rate>10</update_rate>

    <ray>
      <scan>
        <horizontal>
          <samples>720</samples>
          <resolution>1</resolution>
          <min_angle>-3.14159</min_angle>
          <max_angle>3.14159</max_angle>
        </horizontal>
      </scan>

      <range>
        <min>0.12</min>
        <max>8.0</max>
        <resolution>0.01</resolution>
      </range>
    </ray>

    <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
      <topicName>scan</topicName>
      <frameName>laser_link</frameName>
    </plugin>
  </sensor>
</gazebo>



</robot>

